version: "3"
services:
  postgres:
    image: postgres:14.3
    environment:
      POSTGRES_DB: "app_db"
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root"
    volumes:
      - .:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"